sqaush

diff --git a/bin/init-certs b/bin/init-certs
--- a/bin/init-certs
+++ b/bin/init-certs
@@ -1,36 +1,67 @@
-#!/bin/bash -e
+#!/bin/bash
 BASEDIR=$(readlink -f "$(dirname "$0")")
 STACK="$1"
-DATACENTER="$2"
-CLIENTIP="$3"
+CLIENTIP="$2"
+CERTDIR=${CERTDIR:-"$HOME/.swarmer/$STACK"}
 
-if [ -z "$STACK" ] || [ -z "$DATACENTER" ]; then
-    echo "usage: $BASEDIR/swarmer.sh STACK DATACENTER CLIENTIP"
-    echo "It will generate the CA cert and a client keypair in the $HOME/.swarmer/STACK/DATACENTER directory."
+if [ -z "$STACK" ]; then
+    echo "usage: $BASEDIR/swarmer.sh STACK [CLIENTIP]"
+    echo "It will generate the CA cert and a client cert in the $HOME/.swarmer/STACK directory."
     exit 1
 fi
 
-CERTDIR="$HOME/.swarmer/$STACK/$DATACENTER"
 mkdir -p "$CERTDIR"
 
-if [ ! -z "$(find "$CERTDIR" -type f)" ]; then
+if [ ! -z "$(find "$CERTDIR" -type f -name "*.pem")" ]; then
     echo "$CERTDIR is not empty. Aborting."
     exit 1
 fi
 
+## CN,OU,Hostnames must be named after flocker's convention
+## Ask flockerz : https://github.com/ClusterHQ/flocker/blob/master/flocker/ca/_ca.py
+## Warning! Flocker impl doesn't support wildcard DNS.
+
+OU=$(uuidgen)
+
 cat > "$CERTDIR"/run.sh <<EOF
-cd /certs
-echo '{"CN":"$DATACENTER $STACK","key":{"algo":"rsa","size":4096}}' | cfssl gencert -initca - | cfssljson -bare ca -
-echo '{"signing":{"default":{"expiry":"100000h","usages":["signing","server auth","client auth"]}}}' > req.json
-echo '{"CN":"$DATACENTER $STACK client","hosts":["$CLIENTIP"],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=req.json - | cfssljson -bare "client"
+pushd $CERTDIR
+echo generating CACERT
+echo '{"names":[{"OU":"$OU"}],"CN":"$STACK","key":{"algo":"rsa","size":2048}}' | cfssl gencert -initca - | cfssljson -bare ca -
+echo '{"signing":{"default":{"expiry":"100000h","usages":["client auth"]}}}' > req.json
+echo generating CLIENT Cert
+if [ ! -z "$CLIENTIP" ]; then
+   echo '{"CN":"user-$STACK","names":[{"OU":"$OU"}],"hosts":["$CLIENTIP"],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=req.json -hostname $CLIENTIP - | cfssljson -bare "client"
+else
+   echo '{"CN":"user-$STACK","names":[{"OU":"$OU"}],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=req.json - | cfssljson -bare "client"
+fi
+# move files for docker DOCKER_CERT_PATH compatibiliy
+mv client.pem cert.pem
+mv client-key.pem key.pem
+popd
 EOF
 
 chmod +x "$CERTDIR/run.sh"
-docker run --rm -v "$CERTDIR":/certs --entrypoint /bin/bash cfssl/cfssl -c "/certs/run.sh "
+
+which cfssl > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+    "$CERTDIR/run.sh"
+else
+    which docker > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        docker run --rm -v "$CERTDIR":"$CERTDIR" --entrypoint /bin/bash cfssl/cfssl -c "$CERTDIR/run.sh"
+    else
+        echo "couldn't find nor cfssl nor docker binary." >&2
+        exit 1
+    fi
+fi
 
 sudo chown -R "$USER":"$USER" "$CERTDIR"
 find "$CERTDIR" -type f -exec chmod 0600 {} \;
 rm -f "$CERTDIR/run.sh"
-echo "Generating PKCS12 cert to use in browser"
-openssl pkcs12 -inkey "$CERTDIR/client-$CLIENTIP-key.pem" -in "$CERTDIR/client-$CLIENTIP.pem" -export -out "$CERTDIR/client-$CLIENTIP.pfx"
+
+if [ -f "$CERTDIR/cert.pem" ] && [ -f "$CERTDIR/key.pem" ]; then
+    echo "Generating PKCS12 cert to use in browser"
+    openssl pkcs12 -inkey "$CERTDIR/key.pem" -in "$CERTDIR/cert.pem" -export -out "$CERTDIR/client.pfx"
+fi
+
 echo "certs are in $(readlink -f "$CERTDIR")"
diff --git a/bin/node-certs b/bin/node-certs
--- a/bin/node-certs
+++ b/bin/node-certs
@@ -2,37 +2,92 @@
 BASEDIR=$(readlink -f "$(dirname "$0")")
 STACK="$1"
 DATACENTER="$2"
+CERTDIR=${CERTDIR:-"$HOME/.swarmer/$STACK/$DATACENTER"}
+CACERTDIR=${CACERTDIR:-"$HOME/.swarmer/$STACK"}
 shift 2
 HOSTS=($@)
 
-if [ -z "$STACK" ] || [ -z "$DATACENTER" ]; then
+if [ -z "$STACK" ] || [ -z "$DATACENTER" ] || [ -z "$1" ]; then
     echo "usage: $BASEDIR/swarmer.sh STACK DATACENTER [HOST1] [HOST2] ... [HOSTN]"
     echo "It will generate a keypair for each host in the $HOME/.swarmer/STACK/DATACENTER directory."
     exit 1
 fi
 
-CERTDIR="$HOME/.swarmer/$STACK/$DATACENTER"
-
-if [ ! -d "$CERTDIR" ]; then
-    echo "$CERTDIR doesn't exists. Please run init-certs."
+if [ ! -d "$CACERTDIR" ]; then
+    echo "$CACERTDIR doesn't exists. Please run init-certs."
     exit 1
 fi
 
-if [ ! -f "$CERTDIR/ca.pem" ] || [ ! -f "$CERTDIR/ca-key.pem" ]; then
+if [ ! -f "$CACERTDIR/ca.pem" ] || [ ! -f "$CACERTDIR/ca-key.pem" ]; then
     echo "CACERT keypair doesn't exists. Please run init-certs."
     exit 1
 fi
 
+mkdir -p "$CERTDIR"
+
+## CN,OU,Hostnames must be named after flocker's convention
+## Ask flockerz : https://github.com/ClusterHQ/flocker/blob/master/flocker/ca/_ca.py
+## Warning! Flocker impl doesn't support wildcard DNS.
+OU=$(openssl x509 -in "$CACERTDIR/ca.pem" -subject -noout | sed 's/.*OU=\([^\/]*\)\/.*/\1/g')
+
 for i in "${HOSTS[@]}"; do
+    HOST_NAME=${i%:*}
+    HOST_IP=${i#*:}
+    HOSTNAMES="\"$HOST_NAME.node.$DATACENTER.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"control-service\""
+    HOSTNAMES="$HOSTNAMES,\"consul.service.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"consul-agent.service.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"swarm.service.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"registry.service.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"journald.service.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"flocker.service.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"influxdb.service.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"consul.service.$DATACENTER.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"consul-agent.service.$DATACENTER.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"swarm.service.$DATACENTER.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"registry.service.$DATACENTER.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"journald.service.$DATACENTER.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"flocker.service.$DATACENTER.$STACK\""
+    HOSTNAMES="$HOSTNAMES,\"influxdb.service.$DATACENTER.$STACK\""
+    if [[ ! -z "$HOST_IP" ]]; then
+        HOSTNAMES="$HOSTNAMES,\"$HOST_IP\""
+    fi
+
     cat >> "$CERTDIR"/run.sh <<EOF
-cd /certs
+cd $CERTDIR
+
 echo '{"signing":{"default":{"expiry":"100000h","usages":["signing","server auth","client auth"]}}}' > req.json
-echo '{"CN":"$DATACENTER $STACK default","hosts":["$i.node.dev.vagrant","consul.service.dev.vagrant","registry.service.dev.vagrant","swarm.service.dev.vagrant"],"key":{"algo":"rsa","size":4096}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=req.json - | cfssljson -bare "$i"
+echo '{"names":[{"OU":"$OU"}],"CN":"control-service","hosts":[$HOSTNAMES],"key":{"algo":"rsa","size":2048}}' \
+   | cfssl gencert -ca=$CACERTDIR/ca.pem -ca-key=$CACERTDIR/ca-key.pem -config=req.json -hostname $HOSTNAMES - \
+   | cfssljson -bare "$HOST_NAME-control"
+echo '{"signing":{"default":{"expiry":"100000h","usages":["signing"]}}}' > req.json
+echo '{"names":[{"OU":"$OU"}],"CN":"node-$(uuidgen)","key":{"algo":"rsa","size":2048}}' \
+   | cfssl gencert -ca=$CACERTDIR/ca.pem -ca-key=$CACERTDIR/ca-key.pem -config=req.json - \
+   | cfssljson -bare "$HOST_NAME-node"
+
+if [ ! -z "$HOST_IP" ]; then
+   echo '{"CN":"plugin","names":[{"OU":"$OU"}],"hosts":["$HOST_IP"],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=req.json -hostname $HOST_IP - | cfssljson -bare "$HOST_NAME-plugin"
+else
+   echo '{"CN":"plugin","names":[{"OU":"$OU"}],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=req.json - | cfssljson -bare "$HOST_NAME-plugin"
+fi
 EOF
 done
 
 chmod +x "$CERTDIR/run.sh"
-docker run --rm -v "$CERTDIR":/certs --entrypoint /bin/bash cfssl/cfssl -c "/certs/run.sh > /dev/null"
+
+which cfssl > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+    "$CERTDIR/run.sh"
+else
+    which docker > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        docker run --rm -v "$CERTDIR":"$CERTDIR" -v "$CACERTDIR":"$CACERTDIR" --entrypoint /bin/bash cfssl/cfssl -c "$CERTDIR/run.sh"
+    else
+        echo "couldn't find nor cfssl nor docker binary." >&2
+        exit 1
+    fi
+fi
+
 sudo chown -R "$USER":"$USER" "$CERTDIR"
 find "$CERTDIR" -type f -exec chmod 0600 {} \;
 rm -f "$CERTDIR/run.sh"
