Set Registrator to declare only published ports on pub ip

diff --git a/packer/swarm/scripts/registrator-manage b/packer/swarm/scripts/registrator-manage
--- a/packer/swarm/scripts/registrator-manage
+++ b/packer/swarm/scripts/registrator-manage
@@ -2,6 +2,7 @@
 REGISTRATOR_CONTAINER_NAME="registrator"
 REGISTRATOR_VERSION="v6"
 ADMIN_NETWORK="default"
+PUBLIC_NETWORK="default"
 
 if [[ -f "/etc/registrator/registrator.conf" ]]; then
     . /etc/registrator/registrator.conf
@@ -32,6 +33,24 @@ servicename(){
     echo "${REGISTRATOR_CONTAINER_NAME}"
 }
 
+getpubipaddr(){
+    # Keep trying to retrieve IP addr until it succeeds. Timeouts after 1m
+    now=$(date +%s)
+    timeout=$(( now + 60 ))
+    set +e
+    while :; do
+        if [[ $timeout -lt $(date +%s) ]]; then
+            logger -t "$SWARM_CONTAINER_NAME" "Could not retrieve IP Address. Exiting"
+            exit 5
+        fi
+        ip route | grep -q "^PUBLIC_NETWORK"
+        [ $? -eq 0 ] && break
+        sleep 1
+    done
+
+    printf "$(ip route | grep "^$PUBLIC_NETWORK" | sed 's/.*src \([0-9\.]*\) .*/\1/g')"
+}
+
 gethostadminipaddr(){
     # Keep trying to retrieve IP addr until it succeeds. Timeouts after 1m
     now=$(date +%s)
@@ -55,7 +74,7 @@ start() {
     /usr/bin/docker run \
                     -v /var/run/docker.sock:/tmp/docker.sock \
                     --name $(servicename) \
-                    gliderlabs/registrator:${REGISTRATOR_VERSION} -internal=true consul://$(gethostadminipaddr):8500
+                    gliderlabs/registrator:${REGISTRATOR_VERSION} -ip=$(getpubipaddr) consul://$(gethostadminipaddr):8500
 }
 
 stop() {
