lkj

diff --git a/packer/swarmer/scripts/swarm-agent-manage b/packer/swarmer/scripts/swarm-agent-manage
--- a/packer/swarmer/scripts/swarm-agent-manage
+++ b/packer/swarmer/scripts/swarm-agent-manage
@@ -30,21 +30,38 @@ OPTIONS:
 EOF
 }
 
+gethostadminipaddr(){
+    # Keep trying to retrieve IP addr until it succeeds. Timeouts after 1m
+    now=$(date +%s)
+    timeout=$(( now + 60 ))
+    set +e
+    while :; do
+        if [[ $timeout -lt $(date +%s) ]]; then
+            log user.error "Could not retrieve IP Address. Exiting"
+            exit 5
+        fi
+        ip route | grep -q "^$ADMIN_NETWORK"
+        [ $? -eq 0 ] && break
+        sleep 1
+    done
+
+    ip route | grep "^$ADMIN_NETWORK" | sed 's/.*src \([0-9\.]*\) .*/\1/g'
+}
+
 start(){
     log user.info "start"
     rkt run \
-        --volume hosts,kind=host,source=/etc/hosts,readOnly=true \
+        --dns "$(gethostadminipaddr)" \
         --volume certs,kind=host,source=/etc/swarmer/certs,readOnly=true \
         --volume data,kind=host,source=/var/lib/swarm-agent,readOnly=false \
-        --mount volume=hosts,target=/etc/hosts \
         --mount volume=certs,target=/certs \
         --mount volume=data,target=/.swarm \
         --uuid-file-save /var/run/swarm-agent.uuid \
         swarm --exec /swarm -- \
         join --advertise "$(hostname).node.$DATACENTER.$STACK_NAME":2376 \
         --discovery-opt kv.cacertfile=/certs/ca.pem \
-        --discovery-opt kv.certfile=/certs/docker.pem \
-        --discovery-opt kv.keyfile=/certs/docker-key.pem \
+        --discovery-opt kv.certfile=/certs/node.pem \
+        --discovery-opt kv.keyfile=/certs/node-key.pem \
         "consul://consul.service.$DATACENTER.$STACK_NAME:8500/swarm"
 }
 
